# The contents of this file are parsed and made available as
# via `site.*`. So for example, {{ site.title }} can be used
# in a template to get the contents of the `title` key.

imports:
    - archive.yml
    - articles.yml

title: Roman Pronskiy
subtitle: "I'm passionate about tech, PHP, graphs, developer tools, AI, and music. In the past, I led PhpStorm at JetBrains and founded The PHP Foundation."
