# The contents of this file are parsed and made available as
# via `site.*`. So for example, {{ site.title }} can be used
# in a template to get the contents of the `title` key.

imports:
    - archive.yml
    - articles.yml

title: Roman Pronskiy
subtitle: 'I lead PhpStorm at JetBrains and founded The PHP Foundation.'
